# -*- coding: utf-8 -*-
"""train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15LX7aDq8BZxyS5-J1eb5simvAqsdF7OV

## Data Extraction
"""

!pip install yfinance tensorflow statsmodels scikit-learn joblib

# Import libraries
import yfinance as yf
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from statsmodels.tsa.arima.model import ARIMA
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.model_selection import TimeSeriesSplit
import matplotlib.pyplot as plt
import joblib
import warnings
import os

warnings.filterwarnings('ignore')

COMMODITIES = {
    'Brent Oil': 'BZ=F',
    'US Soybeans': 'ZS=F',
    'US Wheat': 'ZW=F'
}
START_DATE = '2015-01-01'
END_DATE = '2026-10-01'
LOOKBACK_WINDOW = 14
N_SPLITS = 3

def fetch_and_prep_data(ticker, start, end):
    # Downloads ticker data
    df = yf.download(ticker, start=start, end=end, progress=False)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.droplevel(1)

    df = df.reset_index().rename(columns={'Close': 'Price'})
    df = df[['Date', 'Price', 'Open', 'High', 'Low', 'Volume']].dropna()

    df['SMA_14'] = df['Price'].rolling(14).mean()
    df['Std_14'] = df['Price'].rolling(14).std()
    return df.dropna().reset_index(drop=True)

def create_sequences(data, lookback):
    # Generates X and y sequences for LSTM consumption.
    X, y = [], []
    for i in range(lookback, len(data)):
        X.append(data[i-lookback:i, 0])
        y.append(data[i, 0])
    return np.array(X), np.array(y)

def build_lstm_model(input_shape):
    # Compiles and returns the LSTM architecture.
    model = Sequential([
        tf.keras.Input(shape=input_shape),
        LSTM(50, return_sequences=True), Dropout(0.2),
        LSTM(50, return_sequences=False), Dropout(0.2), Dense(1)
    ])
    model.compile(optimizer='adam', loss='mse')
    return model

def run_walk_forward_cv(df, n_splits, lookback):
    # Runs TimeSeries cross-validation and returns last fold data for plotting.
    tscv = TimeSeriesSplit(n_splits=n_splits)
    fold_rmse, fold_mae = [], []
    last_fold_data = {}

    print(f"Running Walk-Forward CV ({n_splits} folds)...")
    for fold, (train_idx, test_idx) in enumerate(tscv.split(df), 1):
        train_df, test_df = df.iloc[train_idx].copy(), df.iloc[test_idx].copy()

        # 1. ARIMAX
        exog_train, exog_test = train_df[['SMA_14', 'Std_14']], test_df[['SMA_14', 'Std_14']]
        arimax_fit = ARIMA(train_df['Price'], exog=exog_train, order=(5,1,0)).fit()
        arimax_pred = arimax_fit.predict(start=test_idx[0], end=test_idx[-1], exog=exog_test)

        train_df['ARIMAX_Fitted'] = arimax_fit.fittedvalues
        train_res = (train_df['Price'] - train_df['ARIMAX_Fitted']).values.reshape(-1, 1)

        # 2. LSTM (Train)
        scaler = MinMaxScaler(feature_range=(-1, 1))
        X_train, y_train = create_sequences(scaler.fit_transform(train_res), lookback)
        X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

        lstm_cv = build_lstm_model((X_train.shape[1], 1))
        lstm_cv.fit(X_train, y_train, epochs=20, batch_size=32, verbose=0)

        # 3. LSTM (Predict)
        true_test_res = (test_df['Price'] - arimax_pred).values.reshape(-1, 1)
        combined_res = np.vstack((train_res[-lookback:], true_test_res))

        X_test, _ = create_sequences(scaler.transform(combined_res), lookback)
        X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))

        lstm_pred = scaler.inverse_transform(lstm_cv.predict(X_test, verbose=0)).flatten()

        # 4. Evaluate
        final_pred = arimax_pred.values + lstm_pred
        rmse = np.sqrt(mean_squared_error(test_df['Price'], final_pred))
        mae = mean_absolute_error(test_df['Price'], final_pred)

        fold_rmse.append(rmse)
        fold_mae.append(mae)
        print(f"  Fold {fold}: RMSE = {rmse:.2f} | MAE = {mae:.2f}")

        if fold == n_splits:
            last_fold_data = {'dates': test_df['Date'], 'actuals': test_df['Price'].values, 'preds': final_pred}

    print(f"Average RMSE: {np.mean(fold_rmse):.2f}")
    return last_fold_data

def train_final_and_save(df, name, lookback): # Trains final production models on 100% of the data without shuffling.
    os.makedirs(name, exist_ok=True)

    # 1. Final ARIMAX on 100% of data
    arimax_final = ARIMA(df['Price'], exog=df[['SMA_14', 'Std_14']], order=(5,1,0)).fit()
    df['Residuals'] = df['Price'] - arimax_final.fittedvalues

    # 2. Final Scaler & LSTM on 100% of data
    scaler = MinMaxScaler(feature_range=(-1, 1))
    X_full, y_full = create_sequences(scaler.fit_transform(df[['Residuals']]), lookback)
    X_full = np.reshape(X_full, (X_full.shape[0], X_full.shape[1], 1))

    lstm_final = build_lstm_model((X_full.shape[1], 1))

    # Train on 100% of data. shuffle=False is critical for time series.
    history = lstm_final.fit(X_full, y_full, epochs=20, batch_size=32, shuffle=False, verbose=0)

    # 3. Save Artifacts for Production Inference
    arimax_final.save(os.path.join(name, 'arimax_model.pkl'))
    lstm_final.save(os.path.join(name, 'lstm_residual_model.keras'))
    joblib.dump(scaler, os.path.join(name, 'minmax_scaler.pkl'))
    df.tail(30).to_csv(os.path.join(name, 'latest_historical_data.csv'), index=False)

    return history

def plot_diagnostics(name, fold_data, history): # Generates the prediction and training loss dashboard.

    plt.figure(figsize=(16, 5))

    # Plot 1: Out-of-Sample Predictions
    plt.subplot(1, 2, 1)
    plt.plot(fold_data['dates'], fold_data['actuals'], label='Actual Price', color='blue')
    plt.plot(fold_data['dates'], fold_data['preds'], label='Predicted Price', color='red', linestyle='--')
    plt.title(f"{name}: Final Fold Out-of-Sample Predictions")
    plt.xlabel('Date')
    plt.ylabel('Price')
    plt.legend()
    plt.grid(True)

    # Plot 2: LSTM Training Loss (No validation split used to prevent leakage)
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Training Loss', color='blue')
    plt.title(f"{name}: LSTM Training Loss Curve")
    plt.xlabel('Epoch')
    plt.ylabel('MSE')
    plt.legend()
    plt.grid(True)

    plt.tight_layout()
    plt.show()

def main():
    for name, ticker in COMMODITIES.items():
        print(f"\n{'='*40}\nProcessing: {name} ({ticker})\n{'='*40}")

        df = fetch_and_prep_data(ticker, START_DATE, END_DATE)
        last_fold_data = run_walk_forward_cv(df, N_SPLITS, LOOKBACK_WINDOW)
        history = train_final_and_save(df, name, LOOKBACK_WINDOW)
        plot_diagnostics(name, last_fold_data, history)

if __name__ == "__main__":
    main()